Repository prgrms-web-devcourse/Team_Price_Offer_FE, pull requests merged in 2021-12, with the labels that each got.

#19 ✨feat: IconButton Component 구현
  src/components/templates/IconButton/index.jsx
  src/stories/IconButton.stories.jsx
Labels: 🙋‍♂️ review required, ✨ feat, ✅ completed

#16 ✨ feat: ButtonComponent 구현
  src/components/templates/Button/index.jsx
  src/stories/components/Button.stories.jsx
Labels: 🙋‍♂️ review required, ✨ feat

#20 ✨feat: Selectbox Component 구현
  src/components/templates/Selectbox/index.jsx
  src/stories/components/SelectBox.stories.jsx
Labels: 🙋‍♂️ review required, ✨ feat, ✅ completed

#17 ✨feat: Divider Component 구현
  src/components/templates/Divider/index.jsx
  src/stories/components/Divider.stories.jsx
Labels: 🙋‍♂️ review required, ✨ feat

#18 ✨feat: Modal Component 구현
  src/components/templates/Modal/index.jsx
  src/hooks/useClickAway.js
  src/stories/components/Modal.stories.jsx
  src/stories/hooks/useClickAway.stories.js
Labels: 🙋‍♂️ review required, ✨ feat

#32 ♻️ refactor: selectbox구조변경,오타수정
  src/stories/components/SelectBox.stories.jsx
Labels: ♻️Refactor, 🖐 skip review

#25 ✨ feat: Dialog Component 구현
  src/components/templates/Dialog/index.jsx
  src/stories/components/Dialog.stories.jsx
Labels: 🙋‍♂️ review required, ✨ feat, ✅ completed

#23 ✨feat: MessageComponent 구현
  src/components/templates/Message/index.jsx
  src/stories/components/Message.stories.jsx
Labels: 🙋‍♂️ review required, ✨ feat

#26 ✨ feat : Input Component 구현
  src/components/templates/Input/index.jsx
  src/stories/components/Input.stories.jsx
Labels: 🙋‍♂️ review required, ✨ feat

#27 ✨feat: Radio Component 구현
  src/components/templates/Radio/index.jsx
  src/stories/components/Radio.stories.jsx
Labels: 🙋‍♂️ review required, ✨ feat, ✅ completed

#36 ♻️ refactor: Dialog Component 리팩토리
  src/components/templates/Dialog/index.jsx
  src/stories/components/Dialog.stories.jsx
Labels: ♻️Refactor, 🖐 skip review, ✅ completed

#34 ♻️refactor : Modal Component 포탈 추가
  src/components/templates/Modal/index.jsx
Labels: ♻️Refactor, 🙋‍♂️ review required, ✅ completed

#21 ✨ feat: Image Component 구현
  src/assets/images/no-image_ rectangle-h.png
  src/assets/images/no-image_ rectangle-w.png
  src/assets/images/no-image_square.png
  src/components/templates/Image/index.jsx
  src/stories/components/Image.stories.jsx
Labels: 🙋‍♂️ review required, ✨ feat

#43 Chore/#42_dummydata
  jsconfig.json
  src/data/dummy/categories.js
  src/data/dummy/orderway.js
Labels: 🖐 skip review, ✅ completed, 🌱chore

#49 💄 design: 전역 css layout 등록
  src/pages/_app.jsx
  src/styles/globals.css
Labels: 💄 Design, 🖐 skip review, ✅ completed

#46 ♻️refactor: template component 리팩토리
  src/components/templates/Dialog/index.jsx
  src/components/templates/Image/index.jsx
  src/components/templates/Input/index.jsx
  src/components/templates/Modal/index.jsx
  src/components/templates/Radio/index.jsx
  src/components/templates/Selectbox/index.jsx
  src/stories/components/Dialog.stories.jsx
  src/stories/components/Input.stories.jsx
  src/stories/components/Radio.stories.jsx
  src/stories/components/SelectBox.stories.jsx
Labels: ♻️Refactor, 🙋‍♂️ review required, ✅ completed

#56 🔧config : sass 적용
  next.config.js
  package-lock.json
  package.json
  src/pages/PostingPage.jsx
  src/styles/scss/_mixins.scss
  src/styles/scss/_variables.scss
Labels: 🙋‍♂️ review required, 🔧 config

#61 ✨ feat: togle Button 구현
  src/assets/images/icon/Favorite_light.svg
  src/assets/images/icon/Favorite_like.svg
  src/components/templates/ToggleButton/index.jsx
  src/hooks/useToggle.js
Labels: 🖐 skip review, ✨ feat, ✅ completed

#41 💄 design : Main Page Markup
  package.json
  src/assets/images/icon/Favorite_like.svg
  src/assets/images/icon/category_bestgoods.svg
  src/assets/images/icon/category_book.svg
  src/assets/images/icon/category_furniture.svg
  src/assets/images/icon/category_game.svg
  src/assets/images/icon/category_lifegoods.svg
  src/assets/images/icon/category_petgoods.svg
  src/assets/images/icon/category_share.svg
  src/assets/images/icon/category_sports.svg
  src/assets/images/icon/category_womengoods.svg
  src/assets/images/icon/category_womenwear.svg
  src/components/templates/Banner/index.jsx
  src/pages/Main.jsx
  src/pages/_app.jsx
  src/pages/index.jsx
  src/styles/mainpage.scss
Labels: 💄 Design

#67 ♻️refactor: searchResult Page scss 적용
  package-lock.json
  src/assets/images/icon/filter.svg
  src/assets/images/icon/heart_blank.svg
  src/assets/images/icon/heart_fill.svg
  src/pages/_app.jsx
  src/pages/search.jsx
  src/styles/common/_mixins.scss
  src/styles/common/_variables.scss
  src/styles/common/font.scss
  src/styles/common/globals.scss
  src/styles/common/reset.min.scss
  src/styles/pages/main.scss
  src/styles/pages/search.scss
  src/styles/scss/_variables.scss
Labels: ♻️Refactor, 🖐 skip review, ✅ completed

#53 💄 design: search Result Page Markup
  src/assets/css/search.css
  src/assets/images/icon/filter.svg
  src/assets/images/icon/heart_blank.svg
  src/assets/images/icon/heart_fill.svg
  src/pages/search.jsx
  src/styles/globals.css
Labels: 💄 Design, 🙋‍♂️ review required, ✅ completed

#69 ♻️refactor: MainPage SCSS 리팩토링
  package-lock.json
  src/pages/Main.jsx
  src/pages/_app.jsx
  src/pages/index.jsx
  src/styles/pages/index.scss
  src/styles/pages/main.scss
Labels: ♻️Refactor, 🖐 skip review, ✅ completed

#72 Feature banner component 이미지 동적으로 받기 구현
  src/components/templates/Banner/index.jsx
  src/pages/index.jsx
Labels: ✨ feat

#77 💄 design: breakpoint 변경
  src/data/dummy/productstatus.js
  src/pages/PostingPage.jsx
  src/pages/_app.jsx
  src/pages/posting.jsx
  src/styles/common/_mixins.scss
  src/styles/common/_variables.scss
  src/styles/pages/posting.scss
Labels: 💄 Design, 🖐 skip review

#82 ♻️ refactor: banner component console제거및 filter 함수 수정
  src/components/templates/Banner/index.jsx
Labels: ♻️Refactor

#64 ♻️ refactor: Toglebutton Component
  src/components/templates/ToggleButton/index.jsx
Labels: ♻️Refactor, ✅ completed

#47 💄 design : PostDetailPage Markup
  src/assets/images/icon/offer.svg
  src/pages/PostDetail.jsx
  src/pages/_app.jsx
  src/pages/index.jsx
  src/styles/pages/PostDetail.scss
  src/styles/pages/index.scss
Labels: 💄 Design

#76 💄 design: Message Page Markup
  src/assets/images/icon/fetch.svg
  src/pages/_app.jsx
  src/pages/message.jsx
  src/styles/pages/message.scss
Labels: 💄 Design, 🖐 skip review, ✅ completed

#80 ✨feat : ProductItem 컴포넌트 구현
  src/components/ui/ProductItem/index.jsx
  src/pages/_app.jsx
  src/stories/ui/ProductItem.stories.jsx
  src/styles/ui/productItem.scss
Labels: 🙋‍♂️ review required, ✨ feat

#84 ✨ feat :ProductItem List컴포넌트 구현
  src/components/ui/GoodsItem/index.jsx
  src/components/ui/GoodsList/index.jsx
  src/pages/_app.jsx
  src/pages/index.jsx
  src/stories/ui/GoodsItem.stories.jsx
  src/stories/ui/ProductItem.stories.jsx
  src/styles/ui/goodsItem.scss
  src/styles/ui/goodsList.scss
Labels: 🙋‍♂️ review required, ✨ feat

#87 ✨ feat :ProductItem컴포넌트 구현
  src/components/ui/GoodsItem/index.jsx
  src/styles/ui/goodsItem.scss
Labels: 🖐 skip review, ✨ feat

#85 ✨ feat: Modal UI Component 구현 (로그인, 회원가입)
  src/components/templates/Input/index.jsx
  src/components/templates/Modal/index.jsx
  src/components/ui/ModalLogin.jsx
  src/components/ui/ModalSignup.jsx
  src/pages/_app.jsx
  src/pages/search.jsx
  src/styles/common/_variables.scss
  src/styles/ui/modal.scss
Labels: 🖐 skip review, ✨ feat, ✅ completed

#89 💄design: Posting Page 마크업
  src/components/templates/Input/index.jsx
  src/components/templates/Radio/index.jsx
  src/components/templates/Selectbox/index.jsx
  src/components/templates/Textarea/index.jsx
  src/pages/posting.jsx
  src/styles/pages/posting.scss
Labels: 💄 Design, 🖐 skip review

#75 ✨ feat: Header Component 구현
  src/assets/images/icon/menu_arrow.svg
  src/assets/images/icon/sale.svg
  src/assets/images/icon/search_black.svg
  src/assets/images/icon/search_light.svg
  src/assets/images/icon/user_circle.svg
  src/assets/images/logo.svg
  src/components/templates/IconButton/index.jsx
  src/components/templates/Modal/index.jsx
  src/components/ui/Header/index.jsx
  src/pages/_app.jsx
  src/pages/index.jsx
  src/styles/pages/PostDetail.scss
Labels: 🙋‍♂️ review required, ✨ feat

#92 ✨ feat: Modal UI Component 구현 (회원정보 수정, 가격제안)
  src/assets/images/icon/photo.svg
  src/components/ui/modal/ModalInfoModify.jsx
  src/components/ui/modal/ModalLogin.jsx
  src/components/ui/modal/ModalOffer.jsx
  src/pages/search.jsx
  src/styles/ui/modal.scss
Labels: 🖐 skip review, ✨ feat, ✅ completed

#93 ✨ feat: Modal UI Component 구현 (구매자 확정하기,거래후기,내가 쓴후기,쪽지 보내기, )
  src/assets/images/icon/review_bad.svg
  src/assets/images/icon/review_good.svg
  src/assets/images/icon/review_soso.svg
  src/components/ui/modal/ModalChat.jsx
  src/components/ui/modal/ModalConfirmBuyer.jsx
  src/components/ui/modal/ModalMyReview.jsx
  src/components/ui/modal/ModalWriteReview.jsx
  src/styles/ui/modalConfirmBuyer.scss
  src/styles/ui/modalReview.scss
Labels: 💄 Design, ✅ completed

#52 💄design: Profile Page 마크업
  src/assets/images/icon/profile_arrow.svg
  src/components/templates/Button/index.jsx
  src/pages/_app.jsx
  src/pages/profile/index.jsx
  src/pages/profile/like.jsx
  src/pages/profile/offer.jsx
  src/pages/profile/review.jsx
  src/pages/profile/sale.jsx
  src/styles/pages/profile/index.scss
  src/styles/pages/profile/review.scss
Labels: 💄 Design, 🙋‍♂️ review required

#97 💄design : scss 디테일 수정
  src/pages/PostDetail.jsx
  src/pages/index.jsx
  src/pages/posting.jsx
  src/pages/search.jsx
  src/styles/common/_mixins.scss
  src/styles/common/globals.scss
  src/styles/pages/PostDetail.scss
  src/styles/pages/index.scss
  src/styles/pages/posting.scss
  src/styles/pages/search.scss
Labels: 💄 Design, 🖐 skip review

#98 🔧 config: API Request 설정
  .gitignore
  next.config.js
  src/api/apis.js
  src/api/config/interceptors.js
  src/api/index.js
Labels: 🖐 skip review, 🔧 config

#99 Config: formik setting && 모달 / 모달Content로 컴포넌트 분리
  package.json
  src/components/ui/modal/ModalChat.jsx
  src/components/ui/modal/ModalConfirmBuyer.jsx
  src/components/ui/modal/ModalInfoModify.jsx
  src/components/ui/modal/ModalLogin.jsx
  src/components/ui/modal/ModalMyReview.jsx
  src/components/ui/modal/ModalOffer.jsx
  src/components/ui/modal/ModalSignup.jsx
  src/components/ui/modal/ModalWriteReview.jsx
  src/components/ui/modal/contents/ContentChat.jsx
  src/components/ui/modal/contents/ContentConfirmBuyer.jsx
  src/components/ui/modal/contents/ContentInfoModify.jsx
  src/components/ui/modal/contents/ContentLogin.jsx
  src/components/ui/modal/contents/ContentMyReview.jsx
  src/components/ui/modal/contents/ContentOffer.jsx
  src/components/ui/modal/contents/ContentSignup.jsx
  src/components/ui/modal/contents/ContentWriteReivew.jsx
  src/utils/validation.js
Labels: ✨ feat, 🔧 config

#101 ✨ feat: Login 기능 구현
  src/api/config/interceptors.js
  src/components/templates/Dialog/index.jsx
  src/components/ui/Header/index.jsx
  src/components/ui/modal/contents/ContentLogin.jsx
  src/pages/_app.jsx
  src/utils/storage.js
  src/utils/validation.js
Labels: ✨ feat

#107 ✨ feat: 이미지 업로드 컴포넌트 구현
  .storybook/main.js
  src/components/templates/ImageUploader/index.jsx
  src/stories/components/ImageUploader.stories.jsx
Labels: 🖐 skip review, ✨ feat

#105 ✨ feat: 회원정보수정 기능 구현
  .storybook/main.js
  package-lock.json
  src/components/ui/modal/contents/ContentInfoModify.jsx
  src/styles/ui/modal.scss
Labels: 🖐 skip review, ✨ feat

#109 🐛 fix: 브라우저 에러 처리
  src/components/templates/Banner/index.jsx
  src/components/templates/Input/index.jsx
  src/components/ui/Header/index.jsx
  src/components/ui/modal/ModalLogin.jsx
  src/components/ui/modal/contents/ContentLogin.jsx
  src/pages/index.jsx
Labels: 🐛 Fix

#103 ✨ feat: 회원가입 기능 구현
  package-lock.json
  src/components/templates/Input/index.jsx
  src/components/ui/modal/ModalLogin.jsx
  src/components/ui/modal/contents/ContentSignup.jsx
  src/styles/ui/modal.scss
  src/utils/validation.js
Labels: 🙋‍♂️ review required, ✨ feat

#113 🌱 chore : 상수화 하기
  src/utils/constant/color.js
  src/utils/constant/icon.js
  src/utils/constant/index.js
Labels: 🙋‍♂️ review required, 🌱chore

#119 ✨ feat : 글쓰기(posting) 페이지 기능구현
  src/api/apis.js
  src/assets/images/imgLoad.png
  src/components/templates/Radio/index.jsx
  src/data/dummy/orderway.js
  src/data/dummy/productstatus.js
  src/pages/posting.jsx
  src/styles/pages/posting.scss
  src/utils/validation.js
Labels: ✨ feat

#122 ♻️ refactor : 상수화 변수 이름 upperCase로 변경
  src/utils/constant/color.js
  src/utils/constant/icon.js
Labels: ♻️Refactor

#116 ✨ feat: kakao login redirect 구현
  next.config.js
  src/components/ui/modal/contents/ContentLogin.jsx
Labels: ✨ feat

#127 ✨ feat: Paging Component 구현
  package-lock.json
  src/api/apis.js
  src/assets/images/icon/pagination_arrow_left.svg
  src/assets/images/icon/pagination_arrow_right.svg
  src/components/templates/Button/index.jsx
  src/components/templates/Input/index.jsx
  src/components/templates/Pagination/index.jsx
  src/components/ui/Header/index.jsx
  src/pages/search.jsx
  src/utils/constant/icon.js
Labels: 🙋‍♂️ review required, ✨ feat

#132 ✨ feat: profile 페이지 기능 구현
  src/api/apis.js
  src/components/ui/GoodsItem/index.jsx
  src/components/ui/GoodsList/index.jsx
  src/components/ui/Header/index.jsx
  src/components/ui/modal/contents/ContentInfoModify.jsx
  src/contexts/AuthProvider/actions.js
  src/contexts/AuthProvider/index.jsx
  src/contexts/AuthProvider/initalstate.js
  src/contexts/AuthProvider/reducer.js
  src/contexts/AuthProvider/types.js
  src/data/dummy/goodsList.js
  src/hooks/useConvertTime.js
  src/pages/404.jsx
  src/pages/_error.jsx
  src/pages/profile/[userId]/[pageType].jsx
  src/pages/profile/[userId]/[pagetype].jsx
  src/pages/profile/contents/Like.jsx
  src/pages/profile/contents/Offer.jsx
  src/pages/profile/contents/Review.jsx
  src/pages/profile/contents/Sale.jsx
  src/pages/profile/contents/index.jsx
  src/styles/pages/profile/index.scss
  src/styles/ui/modal.scss
Labels: ✨ feat

#135 ✨feat : Search에 pazination 추가
  src/components/templates/Pagination/index.jsx
  src/pages/search.jsx
Labels: 🙋‍♂️ review required, ✨ feat

#139 🐛 fix: profile page 기능 구현 브랜치 충돌 이슈 해결
  .eslintrc.json
  next.config.js
  src/api/apis.js
  src/components/templates/Dialog/index.jsx
  src/components/ui/Header/index.jsx
  src/components/ui/modal/contents/ContentInfoModify.jsx
  src/contexts/AuthProvider/initalstate.js
  src/data/dummy/goodsList.js
  src/hooks/useConvertTime.js
  src/pages/_error.jsx
  src/pages/oauth/callback/kakao.jsx
  src/pages/profile/[userId]/[pageType].jsx
  src/pages/profile/contents/Like.jsx
  src/pages/profile/contents/Offer.jsx
  src/pages/profile/contents/Review.jsx
  src/pages/profile/contents/Sale.jsx
  src/pages/profile/contents/index.jsx
  src/pages/profile/index.jsx
  src/pages/profile/like.jsx
  src/pages/profile/offer.jsx
  src/pages/profile/review.jsx
  src/pages/profile/sale.jsx
  src/styles/pages/profile/index.scss
  src/styles/ui/modal.scss
Labels: 🐛 Fix

#141 ✨ feat: 프로필 조회 기능 구현
  src/contexts/AuthProvider/actions.js
  src/pages/profile/[userId]/[pageType].jsx
Labels: ✨ feat

#143 ✨ feat: 찜한 게시글 조회 기능 구현
  src/api/apis.js
  src/components/templates/Spinner/index.jsx
  src/pages/profile/[userId]/[pageType].jsx
  src/pages/profile/contents/Like.jsx
Labels: ✨ feat

#145 ✨ feat: 내가 제안한 가격 상품 조회 기능 구현
  src/api/apis.js
  src/pages/profile/contents/Offer.jsx
Labels: ✨ feat

#150 ✨feat : Search 추가 기능 구현
  src/components/ui/GoodsItem/index.jsx
  src/components/ui/GoodsList/index.jsx
  src/components/ui/Header/index.jsx
  src/pages/search.jsx
  src/styles/ui/goodsItem.scss
  src/styles/ui/goodsList.scss
Labels: ✨ feat

#158 🐛 fix: 게시글 상세페이지 버그 수정 및 css수정
  src/components/templates/Avatar/index.jsx
  src/components/templates/Banner/index.jsx
  src/components/templates/Textarea/index.jsx
  src/components/ui/modal/contents/ContentChat.jsx
  src/components/ui/modal/contents/ContentConfirmBuyer.jsx
  src/components/ui/modal/contents/ContentOffer.jsx
  src/pages/post/[id].jsx
  src/pages/posting/[id].jsx
  src/styles/pages/post.scss
  src/styles/ui/modal.scss
  src/styles/ui/modalReview.scss
  src/utils/validation.js
Labels: 🐛 Fix

#160 ♻️ refactor: 주석 및 필요없는 코드 제거
  src/pages/post/[id].jsx
  src/pages/posting/[id].jsx
Labels: ♻️Refactor, 🖐 skip review

#161 ♻️ refactor: goodsList, goodsItem 리팩토리
  .eslintrc.json
  src/api/apis.js
  src/components/templates/Image/index.jsx
  src/components/ui/GoodsItem/index.jsx
  src/components/ui/GoodsList/index.jsx
  src/components/ui/LikeButton/index.jsx
  src/hooks/useConvertTime.js
  src/pages/search.jsx
  src/utils/functions.js
Labels: ♻️Refactor

#164 ✨ feat: 프로필 페이지 상품 리스트 페이징 및 ui처리
  src/api/apis.js
  src/components/ui/GoodsItem/index.jsx
  src/pages/profile/[userId]/[pageType].jsx
  src/pages/profile/contents/Like.jsx
  src/pages/profile/contents/Offer.jsx
  src/pages/profile/contents/Review.jsx
  src/pages/profile/contents/Sale.jsx
  src/pages/profile/contents/index.jsx
Labels: ✨ feat

#136 ✨ feat: Message 기능 구현
  src/api/apis.js
  src/components/templates/Banner/index.jsx
  src/components/templates/Dialog/index.jsx
  src/components/templates/Textarea/index.jsx
  src/components/ui/Header/index.jsx
  src/components/ui/modal/contents/ContentInfoModify.jsx
  src/components/ui/modal/contents/ContentLogin.jsx
  src/pages/message.jsx
  src/pages/message/[id]/[roomId].jsx
  src/styles/pages/index.scss
  src/styles/pages/message.scss
  src/styles/ui/header.scss
  src/styles/ui/modal.scss
Labels: 🙋‍♂️ review required, ✨ feat

#171 🐛 Fix: 게시글 사진, 수정 버그픽스
  src/components/ui/modal/ModalConfirmBuyer.jsx
  src/components/ui/modal/contents/ContentConfirmBuyer.jsx
  src/pages/post/[id].jsx
  src/pages/posting/[id].jsx
Labels: 🐛 Fix

#172 ✨ feat: 배너랑 포스트이미지 분기처리
  src/components/templates/Banner/index.jsx
  src/pages/index.jsx
  src/pages/post/[id].jsx
Labels: ✨ feat

#148 ✨ feat: 카카오 로그인 구현
  next.config.js
  src/components/ui/modal/contents/ContentLogin.jsx
  src/contexts/AuthProvider/actions.js
  src/pages/oauth/callback/kakao.jsx
  src/pages/oauth/kakao.jsx
Labels: ✨ feat, ✅ completed

#173 ✨ feat: 게시글 수정 데이터 받아오기, 리뷰 호버효과 적용
  src/components/templates/Banner/index.jsx
  src/components/ui/modal/ModalConfirmBuyer.jsx
  src/components/ui/modal/ModalWriteReview.jsx
  src/components/ui/modal/contents/ContentWriteReivew.jsx
  src/pages/posting/[id].jsx
Labels: ✨ feat

#174 ♻️ refactor: ProfilePage 리팩토리
  next.config.js
  package-lock.json
  package.json
  src/api/config/useInterceptor.js
  src/api/useApi.js
  src/components/ui/GoodsItem/index.jsx
  src/components/ui/LikeButton/index.jsx
  src/components/ui/modal/contents/ContentWriteReivew.jsx
  src/contexts/AuthProvider/actions.js
  src/contexts/AuthProvider/index.jsx
  src/contexts/AuthProvider/reducer.js
  src/contexts/AuthProvider/types.js
  src/contexts/AxiosProvider/actions.js
  src/contexts/AxiosProvider/index.jsx
  src/contexts/AxiosProvider/reducer.js
  src/contexts/AxiosProvider/types.js
  src/contexts/LoadingProvider/actions.js
  src/contexts/LoadingProvider/index.jsx
  src/contexts/LoadingProvider/reducer.js
  src/contexts/LoadingProvider/types.js
  src/hooks/useAxiosContext.js
  src/hooks/useLoadingContext.js
  src/pages/_app.jsx
  src/pages/profile/[userId]/[pageType].jsx
  src/pages/profile/contents/Like.jsx
  src/pages/profile/contents/Offer.jsx
  src/pages/profile/contents/Review.jsx
  src/pages/profile/contents/Sale.jsx
  src/pages/profile/contents/index.jsx
Labels: ♻️Refactor, ✨ feat

#176 ♻️ refactor: search page 리팩토리
  src/pages/search.jsx
Labels: ♻️Refactor

#180 💄 design: 전체적인 css detail 수정 작업
  src/components/ui/Header/index.jsx
  src/styles/ui/header.scss
Labels: ♻️Refactor

#183 Feature/#124 post detail page
  package.json
  src/components/templates/Button/index.jsx
  src/components/templates/Dialog/index.jsx
  src/components/ui/modal/contents/ContentChat.jsx
  src/components/ui/modal/contents/ContentConfirmBuyer.jsx
  src/components/ui/modal/contents/ContentOffer.jsx
  src/components/ui/modal/contents/ContentWriteReivew.jsx
  src/pages/post/[id].jsx
  src/pages/posting/[id].jsx
  src/styles/pages/post.scss
Labels: ✨ feat

#184 🐛 Fix : alert 버그, 수정버그 수정
  src/components/templates/Dialog/index.jsx
  src/components/ui/modal/contents/ContentWriteReivew.jsx
  src/pages/posting/[id].jsx
Labels: 🐛 Fix

#185 ✨feat : message 페이지 추가 기능 구현
  package-lock.json
  src/assets/images/icon/close.svg
  src/assets/images/icon/message_chatting_empty.svg
  src/pages/message/[id]/[roomId].jsx
  src/styles/pages/message.scss
  src/utils/constant/icon.js
Labels: ✨ feat

#186 💄 design: 전체적인 css detail 수정 작업
  package-lock.json
  src/assets/images/banner/banner1.png
  src/assets/images/banner/banner1_mobile.png
  src/assets/images/banner/banner1_pc.png
  src/assets/images/banner/banner2.png
  src/assets/images/banner/banner2_mobile.png
  src/assets/images/banner/banner2_pc.png
  src/assets/images/banner/banner3.png
  src/assets/images/banner/banner3_mobile.png
  src/assets/images/banner/banner3_pc.png
  src/pages/index.jsx
  src/pages/posting/[id].jsx
  src/styles/common/globals.scss
  src/styles/pages/index.scss
  src/styles/pages/post.scss
  src/styles/pages/posting.scss
  src/utils/constant/images.js
Labels: 💄 Design
